### ISSUE TITLE
Can't compile repo with README's instructions

### ISSUE THREAD

**Issue by rockbruno** [MobileNativeFoundation/index-import#106]
I've followed the README's instructions to build the repo, but I cannot compile the repo as I get errors regarding `PathRemapper` missing. Searched for it in clang/llvm but couldn't find it, where does it come from?

```
/Users/rochab/Downloads/index-import/absolute-unit.cpp:28:5: error: unknown type name 'PathRemapper'
    PathRemapper clangPathRemapper;
    ^
```

**Comment by brentleyjones** [comment]
It comes from the apple version of llvm, which you should get when following this step:
> Checkout the desired release branch of Swift using something like `./swift/utils/update-checkout --clone --scheme release/5.5.`

**Comment by rockbruno** [comment]
Works with `release/5.7` :)
